services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/workspace

    working_dir: /workspace

    ports:
      - "5000:5000"
      - "5001:5001"
      - "8501:8501"
